### ISSUE TITLE
`./configure && make` fails on Debian Jessie

### ISSUE THREAD

**Issue by regularfry** [NetworkBlockDevice/nbd#42] opened 2016-10-27 19:16 UTC
With the 3.14 release tarball, `./configure && make` fails with this error:

```
...
Making all in systemd
make[2]: Entering directory '/home/zander/elixir/nbd/nbd-3.14/systemd'
make[2]: *** No rule to make target 'nbd@.service.tmpl', needed by 'nbd@.service.sh.in'.  Stop.
make[2]: Leaving directory '/home/zander/elixir/nbd/nbd-3.14/systemd'
Makefile:708: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/zander/elixir/nbd/nbd-3.14'
Makefile:424: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by yoe** [comment] 2016-10-31 12:25
already fixed in git HEAD by commit c8a485f. Not going to update past release tarballs, so leaving as is for now. 3.15 (when it is released) will not have this problem.

Closing, as the issue is no longer present in git HEAD.

**Closed by yoe** 2016-10-31 12:25 UTC
