### ISSUE TITLE
blktests(nbd) fails to run with master branch

### ISSUE THREAD

**Issue by ming1** [NetworkBlockDevice/nbd#170] opened 2024-09-26 08:46 UTC
It is observed that [blktests](https://github.com/osandov/blktests) fails to run nbd test when building nbd-client/nbd-server from master branch:

./check nbd   #run it from blktests top dir

And nbd-3.25 works just fine.

**Comment by yoe** [comment] 2024-09-28 09:26
Sorry, I can't reproduce this. With nbd-client from current git HEAD in my path, if I run "sudo ./check nbd", all four tests pass for me.

I'll need a bit more detail to be able to reproduce this, so closing for now, but feel free to reopen with more details.

**Closed by yoe** 2024-09-28 09:26 UTC
